from airflow import DAG 
from airflow.operators.python import PythonOperator 
from datetime import datetime
import random

default_args = {
    'owner': 'Hai',
    'start_date':datetime(2025,10,28)
}

#our DAG
dag = DAG(
    dag_id = 'xcom_ex_ti',
    default_args = default_args, 
    schedule='@daily',
    catchup=False
)

#Task 1: Python task that prints a little bit something 

def task_one_func(ti):
    print("Starting the DAG workflow...")
    ti.xcom_push(key="rng", value = random.randint(0,10))

first_task = PythonOperator(
    task_id = 'first_task',
    python_callable = task_one_func,
    dag = dag,
)

#Task 2: Raise the number from task 1 to power of 2 
#and store the result in xcom for task 3 

def multiply_numbers(ti):
    number_from_task_one = ti.xcom_pull(task_ids='first_task', key = 'rng')
    result = number_from_task_one * number_from_task_one 
    ti.xcom_push(key = 'multi_result', value = result)

second_task = PythonOperator(
    task_id = 'multiplication_task',
    python_callable = multiply_numbers, 
    dag = dag,
)

#Task 3: Pull the results, print on screen 

def print_results(ti):
    number = ti.xcom_pull(task_ids='first_task', key = 'rng')
    result = ti.xcom_pull(task_ids='multiplication_task', key = 'multi_result')
    print("Number generated by first task: ", number)
    print("Result of computation by second task: ", result)

third_task = PythonOperator(
    task_id = 'print_task',
    python_callable = print_results, 
    dag = dag,
)

first_task >> second_task >> third_task